# Generated by Django 3.1.2 on 2020-10-28 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Кошелек',
                'verbose_name_plural': 'Кошельки',
            },
        ),
        migrations.CreateModel(
            name='MoneyIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.PositiveIntegerField()),
                ('deleted', models.BooleanField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='koshelek.account')),
            ],
            options={
                'verbose_name': 'Поступление денег',
                'verbose_name_plural': 'Поступления денег',
            },
        ),
    ]
