version: "3.5"

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      PG_HOST: pg
    volumes:
    - ./money:/app
    ports:
    - 5000:5000
    depends_on:
      - pg

  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: money
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432